<a href="https://colab.research.google.com/github/INSVikrant54/Neural-Network/blob/main/NeuralNetwork_(4).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
import numpy as np

X = [[1, 2, 3, 2.5],
    [2.0, 5.0, -1.0, 2.0],
    [-1.5, 2.7, 3.3, -0.8]]

class Layer_Dense:
  def __init__(self, n_inputs, n_neurons):
    self.weights = 0.10 * np.random.randn(n_inputs, n_neurons)  #multiplying by 0.10 to get values betwwen -1 and 1
    self.biases = np.zeros((1, n_neurons))    # 1- is the shape of bias and also no need for Transpose as np.np.random.randn handles that
  def forward(self, inputs):
    self.output = np.dot(inputs, self.weights) + self.biases

layer1 = Layer_Dense(4 , 5)   #(4- size of shape provided by input, 5- no of neurons we nedd(LITERALLY CAN BE ANY VALUE))
layer2 = Layer_Dense(5 , 2)  #(5- no. neurons output from previous layer, 2- no of neurons we need can be any)

layer1.forward(X)
#print(layer1.output)
layer2.forward(layer1.output)
print(layer2.output)

[[-0.06909066  0.02798375]
 [ 0.0936055   0.05689606]
 [-0.01156536 -0.07235594]]




*   ***def __init__(self)***:: This is a special method called a constructor. It runs automatically when you create a new instance of the class.

*   **self:** This is a required first parameter in class methods. It refers to the specific instance of the object being created, allowing it to keep its own unique data (like its own specific weights and biases).


*   **def forward(self)**:: This is a regular instance method. In deep learning, we name it forward because it represents the "forward pass" where data flows through the layer to produce an output.
*   **pass**: This is a null statement. Python uses it as a placeholder when a statement is syntactically required but you haven't written the logic yet. It literally tells Python to "do nothing."



In [ ]:
import numpy as np

X = [[1, 2, 3, 2.5],
    [2.0, 5.0, -1.0, 2.0],
    [-1.5, 2.7, 3.3, -0.8]]

class Layer_Dense:
  def __init__(self):
    pass
  def forward(self):
    pass

# OBJECT ORIENTED PROGRAMMING


*   It is standard to use 'X' as for inputs or for Training Data Set for ML
*   After inputs we will add '**HIDDEN LAYERS**'- it is called hidden layers bcz as programmers we oursels dont know what values it has and how it changes, as parameters are changed regularly by models and algo (weights and bias).



---
***HOW TO INITILIZE A LAYER*** :
there are 2 methods

*   **Load a Trained Model** -
loading Trained model only means to load the Saved WEIGHTS and BIAS in our layer(just loading the saved weights and bias)
*   **MAKING A NEW NEURAL NETWORK**


1.   FIRST, initilize Weights:
Random values between -1 and +1 (bcz bigger values can explode exponentially like going from 1 -4-10-103-5000 etc),So we need to keep weights low.

we also need to scale the data set like b/w -0.5 and +0.5 , we need to do that to tend to keep wight b/w -1 and +1.
So , we need to scale/Normalize the inputs , so that the meaing stays the same but values get smaller

2.   **Secondly, we tends to keep(initilize) BIAS at 0,**

But in some cases where we have too low valuess ,which can tend to not firing of the neuron and thus can result in DEAD NEURAL NETWORK, so in such cases we need to change the bias values other than 0



**ADDING NEW LAYER**
WHile adding new Layer , our output of the last layer becomes the input of a new layer.

Also we will need new sets of weights and biases for the new layers of neurons

In [ ]:
import numpy as np

#giving inputs in batches
inputs =  [[1, 2, 3, 2.5],
           [2.0, 5.0, -1.0, 2.0],
           [-1.5, 2.7, 3.3, -0.8]]

weights1 = [[0.2 , 0.8 , -0.5 , 1.0],   #weights of 4 diff neuron going to a new single neuron
           [0.5 , -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87]]

biases1 = [2, 3, 0.5]

weights2 = [[0.1 , -0.14 , 0.5],   #weights of 4 diff neuron going to a new single neuron
           [-0.5 , 0.12, -0.33],
           [-0.44, 0.73, -0.13]]

biases2 = [-1, 2, -0.5]

layer1_output = np.dot(inputs, np.array(weights1).T) + biases1
layer2_output = np.dot(layer1_output, np.array(weights2).T) + biases2
print(layer2_output)

[[ 0.5031  -1.04185 -2.03875]
 [ 0.2434  -2.7332  -5.7633 ]
 [-0.99314  1.41254 -0.35655]]


In [ ]:
import numpy as np

#giving inputs in batches
inputs =  [[1, 2, 3, 2.5],
           [2.0, 5.0, -1.0, 2.0],
           [-1.5, 2.7, 3.3, -0.8]]

weights = [[0.2 , 0.8 , -0.5 , 1.0],   #weights of 4 diff neuron going to a new single neuron
           [0.5 , -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87]]

biases = [2, 3, 0.5]

output = np.dot(inputs, np.array(weights).T) + biases
print(output)

As we using lists of lists in Python fow weights and inputs but in backend numpy is converting them into arrays and then using them for dot product.

So, previous we used to so that as we had a vector on inputs and matrix of weights.

BUT ,now for batches we have both inpus and weights both s matrix, so we need to transpose weights so that normal matrix dot product can take place withoour SHAPE ERROR

**Therefore, now as we will use batches, we need to Directly convert list to numpy arrays instead of list of list while calculation** -- needed because we are using transpose of matrix to avoid shape error





In [ ]:
import numpy as np

#giving inputs in batches
inputs =  [[1, 2, 3, 2.5],
           [2.0, 5.0, -1.0, 2.0],
           [-1.5, 2.7, 3.3, -0.8]]

weights = [[0.2 , 0.8 , -0.5 , 1.0],   #weights of 4 diff neuron going to a new single neuron
           [0.5 , -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87]]

biases = [2, 3, 0.5]

output = np.dot(inputs, np.array(weights).T) + biases
print(output)

[[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]]


Now replacing with a sample of inputs to a batch of inputs We prefer Batches because they support parallel calculation

Also we Prefer GPU over CPU in neural networks because cpu has 4-12 cores whereas GPUs has 100s fo theses cores . ALso CPU core is meant for harder calculations , but we need only matrix type calculations

BUT, main reason to use Batches is for Generalizations.- Like normally we only have a sets of input for each neuron but in batches we have multiple sets of inputs (EX- each set might represnt a input for a time instance)

In [ ]:
import numpy as np

inputs = [1, 2, 3, 2.5]
weights = [[0.2 , 0.8 , -0.5 , 1.0],   #weights of 4 diff neuron going to a new single neuron
           [0.5 , -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87]]

biases = [2, 3, 0.5]

#output = np.dot(inputs,weights) + biases
#need to write weight first or we get shape error in below dot product function
output = np.dot(weights, inputs) + biases
print(output)

[4.8   1.21  2.385]


Batch size of 32 is common in most models ,but may vary depending on the model and task
